<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>LogoErp.Reference.Core</AssemblyName>
    <RootNamespace>LogoErp.Reference.Core</RootNamespace>
  </PropertyGroup>
</Project>
