IF OBJECT_ID('dbo.INTEGRATION_IDEMPOTENCY', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.INTEGRATION_IDEMPOTENCY
    (
        ID BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_INTEGRATION_IDEMPOTENCY PRIMARY KEY,
        OPERATION_KEY NVARCHAR(200) NOT NULL,
        OPERATION_TYPE NVARCHAR(100) NOT NULL,
        STATUS NVARCHAR(30) NOT NULL,
        CORRELATION_ID NVARCHAR(100) NULL,
        LOGO_REFERENCE NVARCHAR(100) NULL,
        ERROR_CODE NVARCHAR(100) NULL,
        ERROR_MESSAGE NVARCHAR(2000) NULL,
        RESPONSE_PAYLOAD NVARCHAR(MAX) NULL,
        CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_INTEGRATION_IDEMPOTENCY_CREATED_AT DEFAULT SYSUTCDATETIME(),
        UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_INTEGRATION_IDEMPOTENCY_UPDATED_AT DEFAULT SYSUTCDATETIME()
    );

    CREATE UNIQUE INDEX UX_INTEGRATION_IDEMPOTENCY_OPERATION_KEY
        ON dbo.INTEGRATION_IDEMPOTENCY(OPERATION_KEY);
END;
GO
