<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>LogoErp.Reference.Infrastructure</AssemblyName>
    <RootNamespace>LogoErp.Reference.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogoErp.Reference.Core\LogoErp.Reference.Core.csproj" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
